replicaCount: 1

image:
  repository: ghcr.io/cpwc/aws-quota-checker
  tag: "master"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources: {}

serviceAccount:
  create: true
  annotations: {}
  automountServiceAccountToken: true

# podMonitor controls the PodMonitor CR (from monitoring.coreos.com/v1)
# This CRD is managed by the prometheus-operator and allows workload to
# get monitored. To use this value, you need to run a `prometheus-operator`
# in the cluster for this value to take effect.
# See https://prometheus-operator.dev/docs/prologue/introduction/
podMonitor:
  # Whether the chart should deploy a PodMonitor.
  # Disabled by default as it requires the PodMonitor CRD to be installed.
  enabled: false
  # additionalLabels to put on the PodMonitor.
  # This is used to be selected by a specific prometheus instance.
  additionalLabels: {}
  # interval is the interval between two metrics scrapes. Defaults to 30s
  interval: 30s

# This gets passed to the container as arguments, add the metrics you want to collect.
extraArgs:
  - vpc_count,ec2_eip_count,vpc_nat_gateways_per_availability_zone
  