apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-quota-checker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-quota-checker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aws-quota-checker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aws-quota-checker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - prometheus-exporter
            {{- range .Values.extraArgs }}
            - {{ . }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ include "aws-quota-checker.fullname" . }}
